import Foundation

public struct EventProperty {
    public static let host = "Host"
    public static let port = "Port"
    public static let timeout = "Timeout"
    public static let timeTaken = "TimeTaken"
    public static let reason = "Reason"
    public static let reasonMessage = "ReasonMsg"
    public static let serverURI = "ServerUri"
    public static let fallbackDelaySeconds = "FallbackDelaySeconds"
    public static let shadowMode = "ShadowMode"
    public static let eventType = "EventType"
    public static let topic = "Topic"
    public static let networkType = "NetworkType"
    public static let libraryType = "LibraryType"
    public static let qos = "QoS"
    public static let sizeBytes = "SizeBytes"
    public static let systemTime = "SystemTime"
    public static let clearState = "ClearState"
    public static let source = "Source"
    public static let clientID = "clientID"
    public static let username = "username"
    public static let scheme = "scheme"
    public static let keepAlive = "keepAlive"
    public static let appState = "AppState"
}

public enum EventName {
    public static let courierConnectStarted = "Courier Connect Started"
    public static let courierConnectSucceeded = "Courier Connect Succeeded"
    public static let courierConnectFailed = "Courier Connect Failed"
    public static let courierReconnect = "Courier Reconnect"
    public static let courierDisconnect = "Courier Disconnect"
    public static let mqttConnectAttempt = "Mqtt Connect Attempt"
    public static let mqttConnectSuccess = "Mqtt Connect Success"
    public static let mqttConnectFailure = "Mqtt Connect Failure"
    public static let mqttConnectionLost = "Mqtt Connection Lost"
    public static let mqttConnectionDisconnect = "Mqtt Disconnect"
    public static let mqttConnectDiscarded = "Mqtt Connect Discarded"
    public static let mqttPingInitiated = "Mqtt Ping Initiated"
    public static let mqttPingTokenNull = "Mqtt Ping Token Null"
    public static let mqttPingSuccess = "Mqtt Ping Success"
    public static let mqttPingFailure = "Mqtt Ping Failure"
    public static let mqttSubscribeAttempt = "Mqtt Subscribe Attempt"
    public static let mqttUnsubscribeAttempt = "Mqtt Unsubscribe Attempt"
    public static let mqttSubscribeSucceess = "Mqtt Subscribe Success"
    public static let mqttSubscribeFailure = "Mqtt Subscribe Failure"
    public static let mqttUnsubscribeFailure = "Mqtt Unsubscribe Failure"
    public static let mqttUnsubscribeSuccess = "Mqtt Unsubscribe Success"
    public static let mqttMessageReceive = "Mqtt Message Receive"
    public static let mqttMessageReceiveFailed = "Mqtt Message Receive Failed"
    public static let mqttMessageSend = "Mqtt Message Send"
    public static let mqttMessageSendSuccess = "Mqtt Message Send Success"
    public static let mqttMessageSendFailed = "Mqtt Message Send Failed"
    public static let connectPacketSend = "Connect Packet Send"
    public static let appActiveTimeTracker = "App Active Time Tracker"
}
