# .github/actions/setup_env/action.yml
name: setup_environment
description: Setup iOS development environment with Ruby, Bundler, and scripts

runs:
  using: "composite"
  steps:
    - name: Load Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.2'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.4'
        bundler-cache: true

    - name: Cache Homebrew packages
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          /usr/local/Cellar
          /opt/homebrew
        key: ${{ runner.os }}-homebrew-${{ hashFiles('Brewfile') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-

    - name: Install Homebrew dependencies
      run: |
        if [ -f "Brewfile" ]; then
          brew bundle install
        else
          echo "No Brewfile found, installing SwiftLint directly"
          brew install swiftlint
        fi
      shell: bash

    - name: Verify Ruby setup
      run: |
        echo "Ruby version: $(ruby --version)"
        echo "Bundler version: $(bundle --version)"
        if command -v swiftlint >/dev/null 2>&1; then
          echo "SwiftLint version: $(swiftlint --version)"
        else
          echo "SwiftLint not found"
        fi
        echo "Current directory: $(pwd)"
        ls -la
      shell: bash

    - name: Install Ruby dependencies
      run: bundle install --jobs 4 --retry 3
      shell: bash

    - name: Create derived data directory
      run: mkdir -p ./.build/derived_data
      shell: bash

    - name: Verify environment
      run: |
        echo "Ruby version: $(ruby --version)"
        echo "Bundler version: $(bundle --version)"
        echo "Working directory: $(pwd)"
        echo "Xcode version: $(xcodebuild -version)"
        echo "Xcode path: $(xcode-select -p)"
        echo "Available Xcode versions:"
        ls /Applications/ | grep -i xcode
        bundle list
      shell: bash
